# Generated by Django 5.0.7 on 2024-07-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Price',
            new_name='price',
        ),
    ]
