# Generated by Django 5.0.7 on 2024-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpatienttodoctor',
            name='status',
            field=models.CharField(choices=[('Visited', 'Visited'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
