# Generated by Django 5.0.7 on 2024-07-30 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0002_rename_price_services_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceType', to='tdc_api.servicetype'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('avilableQuantity', models.PositiveIntegerField()),
                ('material_type', models.CharField(choices=[('consumable', 'Consumable'), ('equipment', 'Equipment'), ('furnishing', 'Furnishing'), ('other', 'other')], max_length=50)),
                ('supplier', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('archiveReason', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialDeletedBy', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
