# Generated by Django 5.0.7 on 2024-07-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0003_alter_services_servicetype_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tdc_api.servicetype'),
        ),
    ]
