# Generated by Django 5.0.7 on 2024-08-01 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0003_alter_services_servicetype_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tdc_api.servicetype'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pID', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=50)),
                ('preferred_language', models.CharField(max_length=70)),
                ('occupation', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, null=True)),
                ('previous_medical_condition', models.CharField(max_length=255, null=True)),
                ('emergency_contact', models.CharField(max_length=40, null=True)),
                ('sergical_history', models.CharField(max_length=255, null=True)),
                ('archive_reason', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_creater', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_delete', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
