# Generated by Django 5.0.7 on 2024-07-31 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0004_alter_material_deletedat_alter_services_servicetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pID', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=50)),
                ('preferredLanguage', models.CharField(max_length=70)),
                ('occupation', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, null=True)),
                ('previousMedicalCondition', models.CharField(max_length=255, null=True)),
                ('emergencyContact', models.CharField(max_length=40, null=True)),
                ('sergicalHistory', models.CharField(max_length=255, null=True)),
                ('archiveReason', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientDeletedBy', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
