# Generated by Django 5.0.7 on 2024-08-01 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdc_api', '0005_assignpatienttodoctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpatienttodoctor',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assigner', to=settings.AUTH_USER_MODEL),
        ),
    ]
